# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
paginate: 10

markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough", "underline"]

title : AllenZhang's Blog
tagline: Site Tagline

keywords : kettle、hadoop、hdfs、hive、hbase、mapreduce、cassandra、fedora、linux、vim、spring、javascript
description: 关注开源、Java、Pentaho、Hadoop、Cassandra
author :
  name : Allen Zhang
  email : 450714009@qq.com
  github : zhqn3720

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://zhqn3720.github.com

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : duoshuo
    disqus :
      short_name :
    livefyre :
      site_id :
    intensedebate :
      account :
    facebook :
      appid :
      num_posts:
      width: 580
      colorscheme: light
    duoshuo :
      name : zhqn3720
      comments :
        num: 5
        avatar : 0
        time: 0
        title : 0
        admin : 0
        length : 14
      visitors :
        num : 15

  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #
  analytics :
    provider : custom
    google :
        tracking_id :
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik

  # Settings for sharing helper.
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : false

  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.

  blogroll : false
  brlist :
    - text : 并行实验室
      url : http://www.parallellabs.com/
    - text : 研究研究
      url : http://www.yanjiuyanjiu.com/
    - text : JavaChen Blog
      url : http://blog.javachen.com/
